### ISSUE TITLE
Alignment and Other Minor fixes

### ISSUE THREAD

**Issue by yadavgaurav251** [yadavgaurav251/Context-Aware-Recommender#8]
Here's the current layout - 

![Screenshot 2020-11-26 at 11 38 45 PM](https://user-images.githubusercontent.com/39044791/100382129-9c1b3100-3040-11eb-9a82-2ecdb7e1c5f4.png)

If we can align the Title of the Movie with the of the poster of the movie , then I think it will look better ( like the heading be in area marked below)
![Screenshot 2020-11-26 at 11 38 45 PM](https://user-images.githubusercontent.com/39044791/100382618-c02b4200-3041-11eb-85ad-5f7db91d24cc.jpg)

Also if possible can we try have different font for the Title of the movie. Plus the spacing is consistent like a little space between Release Date:2008-10-16 Runtime:98 min between them like Release Date: 2008-10-16 Runtime: 98 min ,so kindly make them uniform.

**Comment by blackpandan** [comment]
I am interested can you assign this to me

**Comment by Anishraj10282** [comment]
Done chote!
